# Generated by Django 3.0.11 on 2021-01-19 08:54

from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0174_merge_20201222_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subject', i18nfield.fields.I18nCharField(max_length=255)),
                ('template', i18nfield.fields.I18nTextField()),
                ('all_products', models.BooleanField(default=True)),
                ('include_pending', models.BooleanField(default=False)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('send_offset', models.DurationField(null=True)),
                ('send_offset_days', models.DateField()),
                ('date_is_absolute', models.BooleanField(default=True)),
                ('offset_to_event_end', models.BooleanField(default=False)),
                ('offset_is_after', models.BooleanField(default=False)),
                ('send_to', models.CharField(max_length=10)),
                ('test_field', models.DateTimeField(blank=True)),
                ('limit_products', models.ManyToManyField(to='pretixbase.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sent', models.BooleanField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendmail.Rule')),
                ('subevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.SubEvent')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='subevent',
            field=models.ManyToManyField(through='sendmail.ScheduledMail', to='pretixbase.SubEvent'),
        ),
    ]
