# Generated by Django 3.0.11 on 2021-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='send_offset_days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
