# Generated by Django 3.0.11 on 2021-01-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_auto_20210119_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='test_field',
        ),
    ]
