# Generated by Django 3.0.11 on 2021-01-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0004_auto_20210119_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='send_offset',
        ),
        migrations.AddField(
            model_name='rule',
            name='send_offset_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='send_offset_days',
            field=models.IntegerField(null=True),
        ),
    ]
