# Generated by Django 3.0.11 on 2021-01-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0174_merge_20201222_1031'),
        ('sendmail', '0005_auto_20210125_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event'),
        ),
    ]
