# Generated by Django 3.0.11 on 2021-02-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0174_merge_20201222_1031'),
        ('sendmail', '0006_rule_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event'),
        ),
    ]
